import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Generates and downloads a medical report PDF for a skin scan.
 * @param {Object} result - The scan result object containing disease, confidence, severity, etc.
 * @param {Object} user - The user object containing name and email.
 */
export const downloadMedicalReport = (result, user) => {
    if (!result) return;
    const doc = new jsPDF();
    const date = new Date(result.created_at || new Date()).toLocaleDateString();

    // Title
    doc.setFontSize(22);
    doc.setTextColor(15, 118, 110); // medical-700
    doc.text("SkinAi Medical Report", 105, 20, { align: "center" });

    // Header Info
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Patient Name: ${user?.name || 'Guest'}`, 20, 40);
    doc.text(`Email: ${user?.email || 'N/A'}`, 20, 50);
    doc.text(`Date of Analysis: ${date}`, 20, 60);

    // Analysis Results Table
    autoTable(doc, {
        startY: 70,
        head: [['Category', 'Details']],
        body: [
            ['Detected Condition', result.disease || result.disease_detected],
            ['Confidence Score', `${result.confidence || (result.confidence_score * 100).toFixed(1)}%`],
            ['Severity Level', result.severity || result.severity_level],
        ],
        theme: 'striped',
        headStyles: { fillColor: [15, 118, 110] }
    });

    // Description
    const finalY = doc.lastAutoTable.finalY + 10;
    doc.setFontSize(14);
    doc.text("Description", 20, finalY);
    doc.setFontSize(10);
    const description = result.description || "Analysis complete.";
    const splitDescription = doc.splitTextToSize(description, 170);
    doc.text(splitDescription, 20, finalY + 7);

    // Recommendations
    const recY = finalY + 15 + (splitDescription.length * 5);
    doc.setFontSize(14);
    doc.text("Doctor's Recommendation", 20, recY);
    doc.setFontSize(10);
    const recommendation = result.recommendation || "Consult a dermatologist.";
    const splitRec = doc.splitTextToSize(recommendation, 170);
    doc.text(splitRec, 20, recY + 7);

    // Do/Don't Lists
    let listY = recY + 15 + (splitRec.length * 5);
    const doList = result.doList || result.do_list || [];
    const dontList = result.dontList || result.dont_list || [];

    if (doList.length > 0) {
        doc.setFontSize(14);
        doc.setTextColor(15, 118, 110);
        doc.text("What To Do", 20, listY);
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        doList.forEach((item, index) => {
            doc.text(`${index + 1}. ${item}`, 25, listY + 7 + (index * 6));
        });
        listY += 15 + (doList.length * 6);
    }

    if (dontList.length > 0) {
        if (listY > 260) {
            doc.addPage();
            listY = 20;
        }
        doc.setFontSize(14);
        doc.setTextColor(185, 28, 28); // red-700
        doc.text("What NOT To Do", 20, listY);
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        dontList.forEach((item, index) => {
            doc.text(`${index + 1}. ${item}`, 25, listY + 7 + (index * 6));
        });
    }

    // Disclaimer
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text("Disclaimer: This report is generated by an AI model and should not be considered a final medical diagnosis. Always consult with a licensed dermatologist.", 105, 285, { align: "center" });

    const diseaseName = (result.disease || result.disease_detected || "Report").replace(/\s+/g, '_');
    doc.save(`SkinAi_Report_${diseaseName}.pdf`);
};
