import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const DISPLAY_NAMES = {
    Acne: 'Acne',
    Actinic_Keratosis: 'Actinic Keratosis',
    DrugEruption: 'Drug Eruption',
    Eczema: 'Eczema',
    Fungal_Infection: 'Fungal Infection',
    Infestations_Bites: 'Infestations & Bites',
    Psoriasis: 'Psoriasis',
    Rosacea: 'Rosacea',
    Benign_Growth: 'Benign Growth',
    SkinCancer: 'Skin Cancer',
    Vitiligo: 'Vitiligo',
    Warts: 'Warts',
    Unknown: 'Unknown',
};

const getDisplayName = (cat) => DISPLAY_NAMES[cat] || cat?.replace(/_/g, ' ') || 'Unknown';

/**
 * Generates and downloads a medical report PDF for a skin scan.
 * @param {Object} result - The scan result object.
 * @param {Object} user - The user object containing name and email.
 */
export const downloadMedicalReport = (result, user) => {
    if (!result) return;
    const doc = new jsPDF();
    const date = new Date(result.created_at || new Date()).toLocaleDateString();
    const displayName = getDisplayName(result.category || result.disease || result.disease_detected);

    // Title
    doc.setFontSize(22);
    doc.setTextColor(15, 118, 110);
    doc.text("SkinAi Medical Report", 105, 20, { align: "center" });

    // Disclaimer for uncertain / unknown
    if (result.isUnknown) {
        doc.setFontSize(10);
        doc.setTextColor(180, 80, 0);
        doc.text("Note: The AI could not identify a skin condition from the uploaded image.", 105, 30, { align: "center" });
    } else if (result.confidenceRaw !== undefined && result.confidenceRaw < 0.6) {
        doc.setFontSize(10);
        doc.setTextColor(180, 80, 0);
        doc.text("Note: This result has low confidence. Please consult a dermatologist.", 105, 30, { align: "center" });
    }

    // Header Info
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Patient Name: ${user?.name || 'Guest'}`, 20, 40);
    doc.text(`Email: ${user?.email || 'N/A'}`, 20, 50);
    doc.text(`Date of Analysis: ${date}`, 20, 60);

    // Analysis Results Table
    autoTable(doc, {
        startY: 70,
        head: [['Category', 'Details']],
        body: [
            ['Suggested Condition', displayName],
            ['Confidence Score', `${result.confidence || (result.confidence_score * 100).toFixed(1)}%`],
            ['Severity Level', result.severity || result.severity_level || 'N/A'],
        ],
        theme: 'striped',
        headStyles: { fillColor: [15, 118, 110] }
    });

    // Merged class info
    const includes = result.includes || [];
    let finalY = doc.lastAutoTable.finalY + 10;
    if (includes.length > 0) {
        doc.setFontSize(10);
        doc.setTextColor(80, 80, 150);
        doc.text(`This condition includes: ${includes.join(', ')}`, 20, finalY);
        finalY += 8;
    }

    // Description
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text("Description", 20, finalY);
    doc.setFontSize(10);
    const description = result.description || "Analysis complete.";
    const splitDescription = doc.splitTextToSize(description, 170);
    doc.text(splitDescription, 20, finalY + 7);

    // Recommendations
    const recY = finalY + 15 + (splitDescription.length * 5);
    doc.setFontSize(14);
    doc.text("Doctor's Recommendation", 20, recY);
    doc.setFontSize(10);
    const recommendation = result.recommendation || "Consult a dermatologist.";
    const splitRec = doc.splitTextToSize(recommendation, 170);
    doc.text(splitRec, 20, recY + 7);

    // Do/Don't Lists
    let listY = recY + 15 + (splitRec.length * 5);
    const doList = result.doList || result.do_list || [];
    const dontList = result.dontList || result.dont_list || [];

    if (doList.length > 0) {
        doc.setFontSize(14);
        doc.setTextColor(15, 118, 110);
        doc.text("What To Do", 20, listY);
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        doList.forEach((item, index) => {
            doc.text(`${index + 1}. ${item}`, 25, listY + 7 + (index * 6));
        });
        listY += 15 + (doList.length * 6);
    }

    if (dontList.length > 0) {
        if (listY > 260) {
            doc.addPage();
            listY = 20;
        }
        doc.setFontSize(14);
        doc.setTextColor(185, 28, 28);
        doc.text("What NOT To Do", 20, listY);
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        dontList.forEach((item, index) => {
            doc.text(`${index + 1}. ${item}`, 25, listY + 7 + (index * 6));
        });
    }

    // Disclaimer
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text("Disclaimer: This report is generated by an AI model and provides guidance only. It is not a medical diagnosis. Always consult a licensed dermatologist.", 105, 285, { align: "center" });

    doc.save(`SkinAi_Report_${displayName.replace(/\s+/g, '_')}.pdf`);
};
